Fix SQL script: Remove updated_at column from categories insert
The categories table doesn't have an updated_at column in the schema.
Removed updated_at references from:
- INSERT statement column list
- VALUES clauses
- ON CONFLICT DO UPDATE clauses

This fixes the error:
ERROR: column "updated_at" of relation "categories" does not exist